## $Y_{ij} = \sin(W_{ijk}X_k + B_{ij})$

In [1]:
import torch
import torch.nn as nn
import numpy as np
from neuralop.models import FNO
from torch.utils.data import DataLoader, TensorDataset

In [2]:
K = 5          # input dimension
I, J = 5, 5   # output matrix size
N_train = 4000
N_test = 1
BATCH = 32
EPOCHS = 30
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
W_true = np.random.randn(I, J, K)
B_true = np.random.randn(I, J)

def true_operator(X):
    Z = np.tensordot(W_true, X, axes=([2], [0]))
    return np.sin(Z + B_true)

# -----------------------------
# Dataset
# -----------------------------
X_train = []
Y_train = []

for _ in range(N_train):
    X = np.random.randn(K)
    Y = true_operator(X)
    X_train.append(X)
    Y_train.append(Y)

X_train = torch.tensor(X_train, dtype=torch.float32)
Y_train = torch.tensor(Y_train, dtype=torch.float32)

X = X_train.unsqueeze(1)                                     # (N, 1, K)

# Output is flattened to a single channel over 2D grid
Y = Y_train.unsqueeze(1)                                     # (N, 1, I, J)

loader = DataLoader(
    TensorDataset(X, Y),
    batch_size=BATCH,
    shuffle=True
)

In [5]:
model = FNO(
    n_modes=(3,),          # 1D operator
    hidden_channels=32,
    in_channels=1,
    out_channels=I * J,    # flatten matrix output
    n_layers=4
).to(device)


optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()

In [6]:
for epoch in range(EPOCHS):
    total = 0.0
    for xb, yb in loader:
        xb = xb.to(device)               # (B,1,5)
        yb = yb.to(device)               # (B,1,5,5)

        optimizer.zero_grad()

        # FNO output: (B, out_channels, K)
        y_pred = model(xb)

        # reshape to matrix
        y_pred = y_pred.mean(dim=-1)     # (B, I*J)
        y_pred = y_pred.view(-1, 1, I, J)

        loss = loss_fn(y_pred, yb)
        loss.backward()
        optimizer.step()

        total += loss.item()

    print(f"Epoch {epoch:02d} | Loss {total/len(loader):.4e}")

/home/anshul-jawale/Anshul/Code/Moving-Mirror/env/lib/python3.12/site-packages/tltorch/factorized_tensors/factorized_tensors.py:66: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:306.)
  return self.__class__(self.tensor[indices])
/home/anshul-jawale/Anshul/Code/Moving-Mirror/env/lib/python3.12/site-packages/neuralop/layers/spectral_convolution.py:468: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internal

Epoch 00 | Loss 4.5364e-01
Epoch 01 | Loss 3.8223e-01
Epoch 02 | Loss 3.0680e-01
Epoch 03 | Loss 2.4893e-01
Epoch 04 | Loss 2.1294e-01
Epoch 05 | Loss 1.8858e-01
Epoch 06 | Loss 1.7086e-01
Epoch 07 | Loss 1.5955e-01
Epoch 08 | Loss 1.4861e-01
Epoch 09 | Loss 1.3874e-01
Epoch 10 | Loss 1.3300e-01
Epoch 11 | Loss 1.2765e-01
Epoch 12 | Loss 1.2162e-01
Epoch 13 | Loss 1.1637e-01
Epoch 14 | Loss 1.1174e-01
Epoch 15 | Loss 1.0883e-01
Epoch 16 | Loss 1.0484e-01
Epoch 17 | Loss 1.0281e-01
Epoch 18 | Loss 9.9336e-02
Epoch 19 | Loss 9.6154e-02
Epoch 20 | Loss 9.4572e-02
Epoch 21 | Loss 9.3692e-02
Epoch 22 | Loss 9.1002e-02
Epoch 23 | Loss 8.8159e-02
Epoch 24 | Loss 8.6591e-02
Epoch 25 | Loss 8.4465e-02
Epoch 26 | Loss 8.3221e-02
Epoch 27 | Loss 8.1742e-02
Epoch 28 | Loss 7.9796e-02
Epoch 29 | Loss 7.7976e-02


In [7]:
X_test = torch.randn(1, 1, K).to(device)

with torch.no_grad():
    Y_pred = model(X_test)
    Y_pred = Y_pred.mean(dim=-1).view(I, J).cpu().numpy()

Y_true = true_operator(X_test.cpu().numpy()[0, 0])

Y_pred - Y_true

array([[ 0.10915356,  0.17906929, -0.19051919,  0.03922069,  0.07063051],
       [-0.02622601, -0.13900259,  0.39370847, -0.12961866,  0.07479617],
       [-0.03987223, -0.21119559, -0.05500382,  0.2733896 , -0.06812134],
       [ 0.01716842, -0.11125943,  0.08527027,  0.08108138,  0.14047457],
       [ 0.07567416,  0.07663055,  0.12094518,  0.08287014, -0.03806885]])

## Testing for the case where W, B and output Y can take complex values

In [21]:
W = torch.randn(I, J, K, dtype=torch.complex64)
B = torch.randn(I, J, dtype=torch.complex64)

def true_operator_complex(X):
    """
    X: (K,) real
    returns Y: (I,J) complex
    """
    Z_real = np.tensordot(W_real, X, axes=([2],[0])) + B_real
    Z_imag = np.tensordot(W_imag, X, axes=([2],[0])) + B_imag

    Z = Z_real + 1j * Z_imag
    Y = np.sin(Z)   # complex sine
    return Y

In [22]:
X_list, Y_list = [], []

for _ in range(N_train):
    X = np.random.randn(K)              # real
    Y = true_operator_complex(X)        # complex

    X_list.append(X)
    Y_list.append(np.stack([Y.real, Y.imag], axis=0))

X = torch.tensor(X_list, dtype=torch.float32)      # (N, K)
Y = torch.tensor(Y_list, dtype=torch.float32)      # (N, 2, I, J)

# neuralop input shape: (batch, channels, spatial_dim)
X = X.unsqueeze(1)                                  # (N, 1, K)

loader = DataLoader(
    TensorDataset(X, Y),
    batch_size=BATCH,
    shuffle=True
)

In [23]:
model = FNO(
    n_modes=(3,),          # 1D operator (k-direction)
    hidden_channels=32,
    in_channels=1,         # real X
    out_channels=2 * I * J,  # Re(Y) and Im(Y) flattened
    n_layers=4
).to(device)

# -----------------------------
# Loss and optimizer
# -----------------------------
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()

In [24]:
for epoch in range(EPOCHS):
    total = 0.0
    for xb, yb in loader:
        xb = xb.to(device)     # (B,1,5)
        yb = yb.to(device)     # (B,2,5,5)

        optimizer.zero_grad()

        # FNO output: (B, out_channels, K)
        y_pred = model(xb)

        # Reduce spatial dimension
        y_pred = y_pred.mean(dim=-1)    # (B, 2*I*J)

        # Reshape to (B,2,I,J)
        y_pred = y_pred.view(-1, 2, I, J)

        loss = loss_fn(y_pred, yb)
        loss.backward()
        optimizer.step()

        total += loss.item()

    print(f"Epoch {epoch:02d} | Loss {total/len(loader):.4e}")

/home/anshul-jawale/Anshul/Code/Moving-Mirror/env/lib/python3.12/site-packages/tltorch/factorized_tensors/factorized_tensors.py:66: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:306.)
  return self.__class__(self.tensor[indices])
/home/anshul-jawale/Anshul/Code/Moving-Mirror/env/lib/python3.12/site-packages/neuralop/layers/spectral_convolution.py:468: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internal

Epoch 00 | Loss 2.0488e+05
Epoch 01 | Loss 2.0403e+05
Epoch 02 | Loss 2.0128e+05
Epoch 03 | Loss 1.9631e+05
Epoch 04 | Loss 1.9452e+05
Epoch 05 | Loss 2.6310e+05
Epoch 06 | Loss 2.0465e+05
Epoch 07 | Loss 2.0432e+05
Epoch 08 | Loss 2.0347e+05
Epoch 09 | Loss 2.0011e+05
Epoch 10 | Loss 1.9173e+05
Epoch 11 | Loss 1.8302e+05
Epoch 12 | Loss 1.7424e+05
Epoch 13 | Loss 1.6595e+05
Epoch 14 | Loss 1.8092e+05
Epoch 15 | Loss 2.0476e+05
Epoch 16 | Loss 2.0462e+05
Epoch 17 | Loss 2.0421e+05
Epoch 18 | Loss 2.0319e+05
Epoch 19 | Loss 2.0108e+05
Epoch 20 | Loss 1.9350e+05
Epoch 21 | Loss 1.7724e+05
Epoch 22 | Loss 1.5383e+05
Epoch 23 | Loss 1.6142e+05
Epoch 24 | Loss 2.0116e+05
Epoch 25 | Loss 1.9499e+05
Epoch 26 | Loss 1.8237e+05
Epoch 27 | Loss 1.5042e+05
Epoch 28 | Loss 1.4305e+05
Epoch 29 | Loss 2.0293e+05


In [27]:
X_test = torch.randn(1, 1, K).to(device)

with torch.no_grad():
    Y_pred = model(X_test)
    Y_pred = Y_pred.mean(dim=-1).view(2, I, J).cpu().numpy()

Y_pred_complex = Y_pred[0] + 1j * Y_pred[1]

Y_true = true_operator_complex(X_test.cpu().numpy()[0, 0])

Y_pred_complex - Y_true

array([[  1.84946362+2.14580398e+00j,  18.36116204-5.62206589e+00j,
          9.58285676-1.33854185e+01j,  17.42657564-7.10370301e-01j,
         11.62002464+1.23845663e+01j],
       [ 54.50913718-5.49835932e+02j, -14.65721048-8.87694821e+00j,
          1.34603473+1.60290143e+00j, -28.78044941+9.74468389e+00j,
        -11.3596498 +1.76663558e+01j],
       [  5.9245351 +2.62439521e+00j,   6.25058309+4.70315489e+00j,
          5.92772301+6.12664479e+00j,   3.94062174-2.54088349e+00j,
         -8.63364311+4.63293482e+00j],
       [  0.52310782+1.70376504e+00j,  -2.76010246+5.73763274e+00j,
         -0.1779792 +2.01902209e+00j,  -4.75051774-1.44392527e+00j,
         -1.25756083+7.72727154e-01j],
       [ -1.05792748+3.59287399e+00j, -20.55984208-2.47988276e+01j,
        -28.17420758-4.81765347e+00j,   0.52657091+1.54677192e-01j,
         -9.81343103-1.26121936e+01j]])

In [28]:
np.abs(Y_pred_complex - Y_true)

array([[2.83284140e+00, 1.92026013e+01, 1.64620950e+01, 1.74410483e+01,
        1.69824161e+01],
       [5.52531264e+02, 1.71357529e+01, 2.09310833e+00, 3.03854099e+01,
        2.10033753e+01],
       [6.47978135e+00, 7.82236888e+00, 8.52488572e+00, 4.68877261e+00,
        9.79815689e+00],
       [1.78226179e+00, 6.36699262e+00, 2.02685145e+00, 4.96511218e+00,
        1.47599678e+00],
       [3.74539104e+00, 3.22131798e+01, 2.85831377e+01, 5.48818691e-01,
        1.59803272e+01]])